---
- name: Register SAP HANA installation status
  stat:
    path: "/hana/shared/{{ hana_sid|upper }}/exe/linuxx86_64/hdb"
  register: hdb_install_status

- name: Fail if SAP HANA is not installed
  fail:
    msg: "SAP HANA is not installed!"
  when: not hdb_install_status.stat.exists

- name: Get the list of provided SAP HANA tenant databases
  set_fact:
    tenant_list: "{{ hana_tenants.split(',') | list | upper }}"

- name: Get SAP HANA Tenants from the system
  shell: |
    set -o pipefail
    su - {{ hana_sid|lower }}adm -c "hdbnsutil -printsysteminformation | grep -v SYSTEMDB"
  register: sysinfo_cmd
  changed_when: false
  when: hana_sid is defined

- name: Create the list of SAP HANA tenant databases directories
  set_fact:
    tenant_cfg_dirs: "{{ tenant_cfg_dirs|default([]) + ['/hana/shared/' ~ hana_sid|upper ~ '/global/hdb/custom/config/DB_' + ten_name] }}"
  loop: "{{ tenant_list | list }}"
  loop_control:
    loop_var: ten_name

- name: Validate SAP HANA tenant databases existence
  stat:
    path: "{{ ten_cfg_file }}"
  register: found_res
  failed_when: not found_res.stat.exists
  loop: "{{ tenant_cfg_dirs | list }}"
  loop_control:
    loop_var: ten_cfg_file

- name: Create the list of SAP HANA configuration files for tenant databases
  set_fact:
    tenant_cfg_files: "{{ tenant_cfg_files|default([]) + ['/hana/shared/' ~ hana_sid|upper ~ '/global/hdb/custom/config/DB_' + ten_name + '/global.ini'] }}"
  loop: "{{ tenant_list | list }}"
  loop_control:
    loop_var: ten_name
  when: ten_name in sysinfo_cmd.stdout

- name: Create the global.ini files for tenant databases if missing
  ansible.builtin.file:
    path: "{{ tenant_cfg_file }}"
    owner: "{{ hana_sid | lower }}adm"
    group: sapsys
    mode: '0644'
    state: touch
  loop: "{{ tenant_cfg_files | list }}"
  loop_control:
    loop_var: tenant_cfg_file
...
